# Generated by Django 3.2.13 on 2022-07-27 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_books', '0003_auto_20220724_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estante',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='estanteria_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='libroguardado',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='libro_leido_creation', to=settings.AUTH_USER_MODEL),
        ),
    ]
