# Generated by Django 3.2.13 on 2022-07-15 21:36

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(help_text='Nombre del Autor del Libro', max_length=150, verbose_name='Nombre')),
                ('apellido', models.CharField(help_text='Apellido del Autor del Libro', max_length=150, verbose_name='Apellido')),
                ('pais', models.CharField(blank=True, help_text='País nacimiento del Autor', max_length=150, null=True, verbose_name='País')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
