# Generated by Django 3.2.13 on 2022-07-24 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_libro_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(help_text='Autor del libro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autor_libro', to='books.autor'),
        ),
    ]
